name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: debian-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      #- run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      #- run: brew install ffmpeg
      #- run: brew update && brew upgrade ffmpeg
      #- run: ffmpeg -i movie.mp4 -f apng -vf "chromakey=0xffffff:0.01:0.2" output.png
      - run: apt-get install emcc
      - run: emcc -o wasm/hello.html wasm/hello.c -O3 --shell-file wasm/shell_minimal.html
      - run: git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add wasm/hello.html
          git add wasm/hello.wasm
          git add wasm/hello.js
          git commit -m "<commit message>"
          git remote set-url origin https://<username>:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin main
          git push origin main
